config/routes.rb
PaperLess::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root :to => "dashboard#index"
  
  resources :users do 
    collection do
      post 'change_role'
    end
    resources :orders
    
    resources :folders
  end

  resources :folders, :shallow => true, :except => [:new, :create] do
    collection do 
      get 'get_folders'
      get 'get_html'
      get 'get_folder_list'
      post 'move_folder'
    end
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
    resources :zip_uploaders
  end


  
  resources :orders do 
  	collection do
  		post 'guest_order'
  	end
  	resources :notes
    resources :zip_uploaders do 
      collection do 
        get 'files'
      end
    end
  end
  resources :notes
  resources :zip_uploaders, only: [] do
    member do
      get 'download'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :phone
  
  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :orders
  has_many :folders
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_filter :authenticate_user!

  def index
    authorize current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    # authorize! :update, @user, :message => 'Not authorized as an administrator.'
    authorize current_user
    @user = User.find(params[:id])
    # if @user.update_attributes(params[:user], :as => :admin)
    user_role = @user.user_roles.first
    user_role.role_id = params[:user][:role_ids].to_i
    if user_role.save
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize :user
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
        <div class="modal-header">
          <a class="close" data-dismiss="modal">&#215;</a>
          <h3>Change Role</h3>
        </div>
        <div class="modal-body" style="margin-left: 10%;">
          <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Change Role", :class => "btn" %>
          <a class="btn" data-dismiss="modal" href="#">Close</a>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Users
  </div>
  <div class="panel-body">
    <table class="list-table table table-condensed">
      <thead>
        <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Registered</th>
          <th>Role</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.username, folders_path({user_id: user}) %></td>
            <td><%= user.email %></td>
            <td><%= user.created_at.to_date %></td>
            <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
            <td>
              <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
              <%= render user %>
              <%= link_to "Orders", user_orders_path(user) %>
              <% if !user.roles.where(name: ["Super Admin", "Admin"]).any? %> 
                <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.username %></p>
<p>Email: <%= @user.email if @user.email %></p>