config/routes.rb
PaperLess::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root :to => "dashboard#index"
  
  resources :users do 
    collection do
      post 'change_role'
    end
    resources :orders
    
    resources :folders
  end

  resources :folders, :shallow => true, :except => [:new, :create] do
    collection do 
      get 'get_folders'
      get 'get_html'
      get 'get_folder_list'
      post 'move_folder'
    end
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
    resources :zip_uploaders
  end


  
  resources :orders do 
  	collection do
  		post 'guest_order'
  	end
  	resources :notes
    resources :zip_uploaders do 
      collection do 
        get 'files'
      end
    end
  end
  resources :notes
  resources :zip_uploaders, only: [] do
    member do
      get 'download'
    end
  end

end

app/views/shared/_move_folder.html.erb
<div class="modal fade" id="move_modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Move File/Folder</h4>
      </div>
      <%= form_tag(move_folder_folders_path ,method: :post,class: "form-horizontal")  do %>
        <%= hidden_field_tag :move_file_id %>
        <div class="modal-body">
          <div class="row">
            <div class="col-sm-6">
              <p id="name_of_moving_item"></p>
            </div>
            <div class="col-sm-6">
              Move To: <select id="user_folders_select" name="move_to"></select>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag 'Save', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_page_view.html.erb
<%= hidden_field_tag :root_folder_id, @root_folder.id %>
<div class="col-sm-8">
    <p>
      <span class="folder_menu"><%= image_tag('folder_add.png', :alt => "create_a_new_folder") %> <%= link_to "create a new folder", new_folder_folder_path(@folder) %></span>

      <span class="folder_menu"><%= image_tag('file_add.png', :alt => "upload_a_file") %> <%= link_to "upload a file", "javascript:void(0)", class: "open_modal_upload_file", id: "#{@folder.id}" %></span>
    </p>

    <div id="files_and_folders">
      <table class="table table-stripped">
        <thead>
          <th>Name</th>
          <th>Modified</th>
          <th>Action</th>
        </thead>
        <tbody>
          <% @folders.each do |folder| -%>
            <tr>
              <td>
                <%= image_tag('folder.png') %>
                <%= link_to folder.name, folder %>
              </td>
              <td class="file_modified">
                <%= l folder.updated_at, :format => :short %>
              </td>
              <td>
                <%= link_to image_tag('edit.png', :alt => "edit"), edit_folder_path(folder), :title => "edit" %>&nbsp;
                <% if current_user && current_user.roles.where(name: ["Super Admin", "Admin"]).any? %>
                <% else %>
                  <%= link_to image_tag('move.png', :alt => "Move Folder"), "javascript:void(0)", :title => "Move Folder", name: "#{folder.name}" , id: "#{folder.id}-folder" , class: "move-folder-file"%>&nbsp;
                <% end %>
                <%= link_to image_tag('delete.png', :alt => "delete"), folder, :method => :delete, :data => { :confirm => "Are you sure?" }, :title => "delete item" %>
              </td>
            </tr>
          <% end -%>

          <!-- Here are the files in the root table -->
          <% @folder.zip_uploaders.each do |file| -%>
            <tr>
              <% ext = File.extname(file.zip_identifier) %>
              <td>
                <% if ext == '.zip'%>
                  <%= image_tag('zip.png')%>
                <% elsif ext == '.png' || ext == 'jpg' || ext == 'jpeg'%>
                  <%= image_tag('png.png')%>
                <% elsif ext == '.pdf' %>
                  <%= image_tag('pdf.png')%>
                <% elsif ext == '.tar'%>
                  <%= image_tag('tar.png')%>
                <% elsif ext == '.xls'%>
                  <%= image_tag('xls.png')%>
                <% else %>
                  <%= image_tag('file.png')%>
                <% end %>
                <%= file.zip_identifier %>
              </td>
              <td><%= l file.updated_at, format: :short %></td>
              <td>
                <% if ext != ".zip" %>
                  <% if current_user && current_user.roles.where(name: ["Super Admin", "Admin"]).any? %>
                  <% else %>
                    <%= link_to image_tag('move.png', :alt => "Move File"), "javascript:void(0)", :title => "Move File" , name: "#{file.zip_identifier}", id: "#{file.id}-file", class: "move-folder-file" %>&nbsp; |
                  <% end %>
                  <a href='<%= "#{file.zip_url}" %>' target="_blank" >view</a> &nbsp;
                  <%= link_to "download", download_zip_uploader_path(file) %>
                <% else %>
                  <a href='<%= "#{file.zip_url}" %>'>download</a>
                <% end %>
              </td>
            </tr>
          <% end -%>
        </tbody>
      </table>
    </div>
</div>

<%= render "shared/upload_file_popup" %>
<%= render "shared/move_folder" %>

app/views/shared/_popup.html.erb
<div class="modal fade" id="note_modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Post A Note</h4>
      </div>
      <%= form_tag(notes_path ,method: :post,class: "form-horizontal")  do %>
        <%= hidden_field_tag :order_id %>
        <div class="modal-body">
          <label>Your Message:</label>
          <textarea rows="4" autofocus style="width:97%" id="message" name="message" placeholder="Write note here..."></textarea>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag 'Save', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_upload_file_popup.html.erb
<div class="modal fade" id="folder_modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Upload A File</h4>
      </div>
      <%= simple_form_for(ZipUploader.new, url: folder_zip_uploaders_path(@folder), :html => {:class => 'form-horizontal' }) do |f| %>
        <%= hidden_field_tag :folder_id %>
        <div class="form-group">
          <label class="control-label col-sm-2" for="email">Choose File:</label>
          <div class="col-sm-10">
            <%= f.file_field :zip %>
          </div>
        </div>

        <div class="form-group"> 
          <div style="margin-left: 19%;">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>