config/routes.rb
PaperLess::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root :to => "dashboard#index"
  
  resources :users do 
    collection do
      post 'change_role'
    end
    resources :orders
    
    resources :folders
  end

  resources :folders, :shallow => true, :except => [:new, :create] do
    collection do 
      get 'get_folders'
      get 'get_html'
      get 'get_folder_list'
      post 'move_folder'
    end
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
    resources :zip_uploaders
  end


  
  resources :orders do 
  	collection do
  		post 'guest_order'
  	end
  	resources :notes
    resources :zip_uploaders do 
      collection do 
        get 'files'
      end
    end
  end
  resources :notes
  resources :zip_uploaders, only: [] do
    member do
      get 'download'
    end
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :from_date, :name, :no_of_sheets, :sheet_type, :to_date,:email, :phone
  attr_accessor :email, :phone
  belongs_to :user
  has_many :notes
  has_many :zip_uploaders

  validates :from_date, presence: true 
  validates :to_date, presence: true 
  validates :name, presence: true, uniqueness: true
  validates :no_of_sheets, presence: true 
  validates :sheet_type, presence: true 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_filter :authenticate_user!, only: [:index, :show, :create, :edit, :update]
	
	def index
		if params[:user_id].present?
			@user  = User.find(params[:user_id])
			@orders = @user.orders
		else
			@orders = current_user.orders
		end
	end

	def new
		@order = Order.new
	end

	def create
		@order = current_user.orders.build(params[:order])
		if @order.save
			Delayed::Job.enqueue SendEmailsJob.new(@order)
			flash[:success] = "Successfully submitted."
			redirect_to orders_path
		else
			flash[:danger] = "Please Fill All Fields"
			redirect_to :back
		end
	end

	def show
		@order = Order.find(params[:id])
		@notes = @order.notes.order('created_at DESC').includes(:user)
		if current_user.roles.where(name: ["Super Admin", "Admin"]).any?
			@admin = true
		end	
	end

	def edit
		@order = Order.find(params[:id])
	end


	def update
		order = Order.find(params[:id])
		order.update_attributes(params[:order])
		flash[:success] = "Successfully updated."
		redirect_to orders_path
	end

	def guest_order
		user = User.new
		user.email = params[:order][:email]
		user.phone = params[:order][:phone]
		user.password = rand(999999999)
		# cookie used only for the guest user. because there are two ways to signup. 1. signup   2. while posting order as guest then automatically new user regisered and sent an email for reset password if he/she want to continue. at this time no need to sign in.
		cookies[:login_user_as_guest] = "yes"
		if user.save
			role = user.user_roles.build
	    role.role_id = Role.find_by_name('User').id
	    role.save!
			order = user.orders.build(params[:order])
			order.save!
			user.send_reset_password_instructions
      cookies.delete :login_user_as_guest
			# Delayed::Job.enqueue SendEmailsJob.new(order)
			flash[:success]  = "Successfully submitted. Please check your email."
			redirect_to root_url
		else
			flash[:error]  = "Please fill all the fields."
			redirect_to :back
		end
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_orders.html.erb
<div>
<%= link_to "Create Order",new_order_path, class: "btn btn-success btn-mini btn-sm pull-right"%>
</div>
<br/><br/>
<% if orders.present? %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      Orders
    </div>
    <div class="panel-body">
      <table class="list-table table table-condensed">
        <thead>
          <tr>
            <th>Order</th>
            <th>Tot. Sheets</th>
            <th>Sheet Type</th>
            <th>Start date</th>
            <th>Finishing date</th>
            <th># of Files</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        <% orders.each do |order| %>
          <tr>
            <td><%= link_to order.name, order_path(order) %></td>
            <td><%= order.no_of_sheets %></td>
            <td><%= order.sheet_type %></td>
            <td><%= order.from_date.class %></td>
            <td><%= order.to_date %></td>
            <td><%= order.try(:zip_uploaders).try(:count) %></td>
            <td>
              <%#= link_to "View files", files_order_zip_uploaders_path(order), class: "btn btn-sm btn-mini btn-primary"%>
              <%= link_to 'Edit', edit_order_path(order), class: "btn btn-mini btn-sm btn-primary"%>
              <%= link_to("Delete order", order_path(order), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini btn-sm btn-danger disabled') %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>    
    </div>
  </div>
<% else %>
 <p class="flash-msg">No Order Found.<%= link_to "Click Here to post", new_order_path%></p>
<% end %>

app/views/orders/_user_orders.html.erb
<div>
  <strong>User:</strong> <%= user.username %> | <%= user.email %>
  <%= link_to_function image_tag("/assets/back.png",:border => 0), "history.back()" , class: "pull-right" %>
</div>
<br/>
<% if orders.present? %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      Orders
    </div>
    <div class="panel-body">
      <table class="list-table table table-condensed">
        <thead>
          <tr>
            <th>Order</th>
            <th>Tot. Sheets</th>
            <th>Sheet Type</th>
            <th>Start date</th>
            <th>Finishing date</th>
            <th># of Files</th>
            <th># of Notes</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        <% orders.each do |order| %>
          <tr>
            <td><%= link_to order.name, order_path(order) %></td>
            <td><%= order.no_of_sheets %></td>
            <td><%= order.sheet_type %></td>
            <td><%= order.from_date.class %></td>
            <td><%= order.to_date %></td>
            <td><%= order.try(:zip_uploaders).try(:count) %></td>
            <td><%= order.try(:notes).try(:count)%></td>
            <td>
              <%#= link_to "View files", files_order_zip_uploaders_path(order), class: "btn btn-sm btn-mini btn-primary"%>
              <%= link_to "Add Note", "javascript:void(0)", class: "btn btn-mini btn-sm btn-success open_modal", id: "#{order.id}"%>
              <%#= link_to "Upload zip", new_order_zip_uploader_path(order), class: "btn btn-mini btn-sm btn-warning"%>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
 <p class="flash-msg">No Order Found.</p>
<% end %>

<%= render "shared/popup" %>

app/views/orders/edit.html.erb
<%= stylesheet_link_tag "bootstrap-datepicker3" %>
<%= javascript_include_tag 'bootstrap-datepicker', 'date_format'%> 
<div>
  <%= link_to_function image_tag("/assets/back.png",:border => 0), "history.back()" , class: "pull-right" %>
  <h3>Update Order </h3>
</div>
<div style="margin-left: 15%; width:60%;">
  <%= simple_form_for(@order, :html => {:class => 'form-horizontal' }) do |f| %>
    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Order Name:</label>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Tot. Sheets:</label>
      <div class="col-sm-10">
        <%= f.number_field :no_of_sheets, class: "text_field form-control" %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Sheet Type:</label>
      <div class="col-sm-10">
        <%= f.text_field :sheet_type, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Start Date:</label>
      <div class="col-sm-10">
        <%= f.text_field :from_date, class: "form-control datepicker", placeholder: "MM/DD/YYYY" %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Finishing Date:</label>
      <div class="col-sm-10">
        <%= f.text_field :to_date, class: "form-control datepicker",placeholder: "MM/DD/YYYY" %>
      </div>
    </div>

    <div class="form-group"> 
      <div style="margin-left: 19%;">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  <% end %>
</div>
<div class="clearfooter"></div>
</div>

app/views/orders/index.html.erb
<% if @user.present? %>
  <%= render partial: 'user_orders', locals: {user: @user, orders: @orders} %>
<% else %>
  <%= render partial: 'orders', locals: {orders: @orders} %>
<% end %>

app/views/orders/new.html.erb
<%= stylesheet_link_tag "bootstrap-datepicker3" %>
<%= javascript_include_tag 'bootstrap-datepicker', 'date_format'%> 
<div>
  <%= link_to_function image_tag("/assets/back.png",:border => 0), "history.back()" , class: "pull-right" %>
  <h3>Post Order </h3>
</div>
<div style="margin-left: 15%; width:60%;">
  <%= simple_form_for(@order, :html => {:class => 'form-horizontal' }) do |f| %>
    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Order Name:</label>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Tot. Sheets:</label>
      <div class="col-sm-10">
        <%= f.number_field :no_of_sheets, class: "text_field form-control" %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Sheet Type:</label>
      <div class="col-sm-10">
        <%= f.text_field :sheet_type, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Start Date:</label>
      <div class="col-sm-10">
        <%= f.text_field :from_date, class: "form-control datepicker", placeholder: "MM/DD/YYYY" %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Finishing Date:</label>
      <div class="col-sm-10">
        <%= f.text_field :to_date, class: "form-control datepicker",placeholder: "MM/DD/YYYY" %>
      </div>
    </div>

    <div class="form-group"> 
      <div style="margin-left: 19%;">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  <% end %>
</div>
<div class="clearfooter"></div>
</div>

app/views/orders/show.html.erb
<div>
  <strong>Order: </strong> <%= @order.name%> | <%= @order.user.email %>
  <%= link_to_function image_tag("/assets/back.png",:border => 0), "history.back()" , class: "pull-right" %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Order</th>
      <th>Tot. Sheets</th>
      <th>Sheet Type</th>
      <th>Start date</th>
      <th>Finishing date</th>
      <% if @admin %>
        <th># of notes</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @order.name%></td>
      <td><%= @order.no_of_sheets %></td>
      <td><%= @order.sheet_type %></td>
      <td><%= @order.from_date.class %></td>
      <td><%= @order.to_date %></td>
      <% if @admin %>
        <td><%= @order.notes.count%></td>
      <% end %>
    </tr>
  </tbody>
</table>
<div>
  <% if @admin %>
    <% if @notes.present? %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          Notes
        </div>
        <div class="panel-body">  
          <table class="table table-striped">
            <thead>
              <th>Posted By</th>
              <th>Message</th>
            </thead>
            <tbody>
              <% @notes.each do |note| %>
                <tr>
                  <td style="width:16%;background-color: lightgray;"><%= note.user.username %>: </td>
                  <td><%= note.message %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% else %>
      <p class="flash-msg">No Message Found.</p>
    <% end %>
  <% end %>
</div>
<%= link_to "Add Note", "javascript:void(0)", class: "btn btn-mini btn-sm btn-success pull-right open_modal", id: "#{@order.id}" if current_user.roles.where(name: ["Super Admin", "Admin"]).any? %>
<div class="clearfooter"></div>
</div>
<%= render "shared/popup" %>