config/routes.rb
PaperLess::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root :to => "dashboard#index"
  
  resources :users do 
    collection do
      post 'change_role'
    end
    resources :orders
    
    resources :folders
  end

  resources :folders, :shallow => true, :except => [:new, :create] do
    collection do 
      get 'get_folders'
      get 'get_html'
      get 'get_folder_list'
      post 'move_folder'
    end
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
    resources :zip_uploaders
  end


  
  resources :orders do 
  	collection do
  		post 'guest_order'
  	end
  	resources :notes
    resources :zip_uploaders do 
      collection do 
        get 'files'
      end
    end
  end
  resources :notes
  resources :zip_uploaders, only: [] do
    member do
      get 'download'
    end
  end

end

app/models/zip_uploader.rb
class ZipUploader < ActiveRecord::Base
  attr_accessible :order_id, :zip,:folder_id

  belongs_to :folder
  belongs_to :order

  mount_uploader :zip, ZipFileUploader
end

app/controllers/zip_uploaders_controller.rb
class ZipUploadersController < ApplicationController

	def new
		authorize :zip_upload
		@order = Order.find(params[:order_id])
		@zip_upload = @order.zip_uploaders.build
	end

	def create
		# order  = Order.find(params[:order_id])
		# @zip = order.zip_uploaders.build(params[:zip_uploader])
  #   if @zip.save
  #   	flash[:success]  ="successfully uploaded"
  #   	redirect_to request.referrer
  #   else
  #   	flash[:danger] = "Something went wrong."
  #   	redirect_to :back
  #   end


  # following code integratde with folder
		folder  = Folder.find(params[:folder_id])
		@zip = folder.zip_uploaders.build(params[:zip_uploader])
    if @zip.save
    	flash[:success]  ="successfully uploaded"
    	redirect_to request.referrer
    else
    	flash[:danger] = "Something went wrong."
    	redirect_to :back
    end


	end

	def files
		@order = Order.find(params[:order_id])
		@files  = @order.zip_uploaders
	end

	def download
		file = ZipUploader.find(params[:id])
		url = file.zip.url
		data = open(url).read
		send_data data, :disposition => 'attachment', :filename=> "#{file.zip_identifier}"
	end
end

app/views/zip_uploaders/files.html.erb
<div>
  <strong>Order: </strong> <%= @order.name%> | <%= @order.user.email %>
  <%= link_to_function image_tag("/assets/back.png",:border => 0), "history.back()" , class: "pull-right" %>
</div>
<br/>
<% if @files.present? %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        Files
      </div>
      <div class="panel-body">
        <table class="list-table table table-striped">
          <thead>
            <th>File Name</th>
            <th>Actions</th>
          </thead>
          <tbody>
            <% @files.each do |file| %>
              <tr>
                <td><%= file.zip_identifier %></td>
                <% ext = File.extname(file.zip_identifier) %>
                <td>
                  <% if ext != ".zip" %>
                     <a href='<%= "#{file.zip_url}" %>' target="_blank" class="btn btn-sm btn-mini btn-success">view</a>
                    <%= link_to "download", download_zip_uploader_path(file), class: "btn btn-sm btn-mini btn-primary"%>
                  <% else %>
                    <a href='<%= "#{file.zip_url}" %>' class="btn btn-sm btn-mini btn-primary">download</a>
                  <% end %>
                  
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
<% else %>
 <p class="flash-msg">No File Found.<%= link_to "Click Here to upload", new_order_zip_uploader_path(@order) if current_user.roles.where(name: ["Super Admin", "Admin"]).any? %></p>
<% end %>

app/views/zip_uploaders/new.html.erb
<div>
  <strong>Order: </strong> <%= @order.name%> | <%= @order.user.email %>
  <%= link_to_function image_tag("/assets/back.png",:border => 0), "history.back()" , class: "pull-right" %>
</div>
<h3>Upload File</h3> 
<div style="margin-left: 15%; width:60%;">
  <%= simple_form_for(@zip_upload, url: order_zip_uploaders_path(@order) , :html => {:class => 'form-horizontal' }) do |f| %>
    <%#= hidden_field_tag :order_id, @order.id %>
    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Choose File:</label>
      <div class="col-sm-10">
        <%= f.file_field :zip %>
      </div>
    </div>

    <div class="form-group"> 
      <div style="margin-left: 19%;">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  <% end %>
</div>
<div class="clearfooter"></div>
</div>